charts/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^barcharts/$', views.barcharts_view, name='bar_charts'),
    url(r'^testjson/$', views.test_json, name='test_json'),
    url(r'^piecharts/$', views.piecharts_view, name='pie_charts'),
    url(r'^testjsonpie/$', views.test_json_pie, name='test_json_pie'),
    url(r'^professions/$', views.death_by_profession, name='professions'),
    url(r'^deaths/$', views.death_by_death, name='deaths'),
]

totetiroler/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('webpage.urls', namespace='webpage')),
    url(r'^accounts/', include('account.urls', namespace='account')),
    url(r'^places/', include('places.urls', namespace='places')),
    url(r'^persons/', include('persons.urls', namespace='persons')),
    url(r'^datamodel/', include('django_spaghetti.urls', namespace='datamodel')),
    url(r'^browsing/', include('browsing.urls', namespace='browsing')),
    url(r'^charts/', include('charts.urls', namespace='charts')),
    url(r'^social-auth/', include('social.apps.django_app.urls', namespace='social')),
]

charts/models.py
from django.db import models

# Create your models here.

charts/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.db.models import Count
from persons.models import Person, Beruf, Todesart

DATA = {"status": "ok",
        "query": "api:graph",
        "timestamp": "2016-07-21T09:56:36.803Z",
        "items": "7",
        "title": "LASK4EVER",
        "subtitle": "This is just a test to check if everythin works as expected.",
        "legendx": "Club",
        "legendy": "# of Victories",
        "measuredObject": "Victories",
        "payload": [
            ["LASK", 10],
            ["Real Madrid", 4],
            ["Rapid Wien", 0],
            ["Blau Weiß Linz", -10]
        ]
        }

DATA_PIECHART = {
    "items": "2",
    "title": "LASK4EVER",
    "subtitle": "This is just a test.",
    "measuredObject": "# of Victories",
    "payload": [
        ["LASK", 9], ["Blau Weiß Linz", 1]
    ]
}


def death_by_profession(request):
    persons = Person.objects.values('beruf').annotate(total=Count('beruf_id')).order_by('-total')
    payload = []
    for x in persons:
        temp_beruf = Beruf.objects.get(id=int(x['beruf']))
        entry = [temp_beruf.name.title(), x['total']]
        payload.append(entry)

    data = {"items": len(Person.objects.all()),
            "title": "Gefallene nach Berufsgruppe",
            "subtitle": "Gefallene nach Berufsgruppe",
            "legendx": "Berufsgruppe",
            "legendy": "Anzahl der Gefallenen",
            "measuredObject": "Gefallene",
            "payload": payload
            }
    return JsonResponse(data)


def death_by_death(request):
    persons = Person.objects.values('todesart').annotate(total=Count('todesart_id')).order_by('-total')
    payload = []
    for x in persons:
        temp_death = Todesart.objects.get(id=int(x['todesart']))
        entry = [temp_death.name, x['total']]
        payload.append(entry)

    data = {"items": len(Person.objects.all()),
            "title": "Gefallene nach Todesart",
            "subtitle": "Gefallene nach Todesart",
            "legendx": "Todesart",
            "legendy": "Anzahl der Gefallenen",
            "measuredObject": "Gefallene",
            "payload": payload
            }
    return JsonResponse(data)


def barcharts_view(request):
    context = {"test": "test"}
    return render(request, 'charts/bar_charts.html', context)


def piecharts_view(request):
    context = {"test": "test"}
    return render(request, 'charts/pie_charts.html', context)


def test_json(request):
    data = DATA
    return JsonResponse(data)


def test_json_pie(request):
    data = DATA_PIECHART
    return JsonResponse(data)

charts/templates/charts/bar_charts.html
{% extends "webpage/base.html" %}
{% load staticfiles %}
{% block Titel %}some charts{% endblock %}

{% block scriptHeader %}
    <!--highcharts -->
        <script src="{% static 'charts/highcharts/highcharts.js' %}"></script>
        <script src="{% static 'charts/highcharts/highcharts-3d.js' %}"></script>
        
        <script src="{% static 'charts/highcharts/exporting.js' %}"></script>
    <!--highcharts END -->
{% endblock %}
{% block content %}
<div class="panel panel-default" style="text-align:center">
    <div class="panel-heading"><h1>Bitte wählen Sie</h1><br/>
        <select id="chartselector" class="form-control">
                <option value="---">---</option>
                <option value="{% url 'charts:professions' %}">Gefallene nach Beruf</option>
                <option value="{% url 'charts:deaths' %}">Gefallene nach Todesart</option>
        </select>
    </div>
    <div class="panel-body">
        <div id="bar"/>
    </div>
</div>
    
{% endblock %}
{% block scripts %}
    <script type="text/javascript">
        $("#chartselector").change(function(){
            var which_chart = $("#chartselector option:selected").val();
            console.log(which_chart);
            $.getJSON( which_chart, function( data ) {
                $('html, body').css("cursor", "default");        
                var items = data.payload;
                var measuredObject = data.measuredObject
                var header = data.title;
                $("h1").text(header);
                console.log(items);
                $(function () {
                    $('#bar').highcharts({
                    chart: {
                        type: 'column',
                        options3d: {
                                enabled: true,
                                alpha: 15
                            }
                    },
                    title: {
                        text: ""
                        },
                    subtitle: {
                        text: data.subtitle
                        },
                    xAxis: {
                        type: 'category',
                        labels: {
                        rotation: -45,
                        style: {
                        fontSize: '13px',
                        fontFamily: 'Verdana, sans-serif'
                        }
                        }
                        },
                    yAxis: {
                        min: -10,
                        title: {
                        text: data.legendy
                        }
                    },
                    legend: {
                        enabled: false
                        },
                    tooltip: {
                    },
                    series: [{
                    name: measuredObject,
                    data: items,
                    dataLabels: {
                    enabled: false,
                    rotation: -90,
                    color: '#FFFFFF',
                    align: 'right',
                    format: '{point.y:.1f}', // one decimal
                    y: 10, // 10 pixels down from the top
                    style: {
                    fontSize: '13px',
                    fontFamily: 'Verdana, sans-serif'
                    }
                    }
                    }]
                    });
                });
            });
        });
    </script>
    <script type="text/javascript" src="{% static 'webpage/libraries/bootstrap335/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'webpage/libraries/bootstrap335/js/bootstrap-tab.js' %}"></script>
    <!-- scroll-up-bottom -->        
    <script type="text/javascript">
            // Setup plugin with default settings
            $(document).ready(function() {
                $.apScrollTop({
                    'onInit': function(evt) {
                        console.log('apScrollTop: init');
                    }
                });
            });
    </script>    
{% endblock %}

charts/templates/charts/pie_charts.html
{% extends "webpage/base.html" %}
{% load staticfiles %}
{% block Titel %}some charts{% endblock %}

{% block scriptHeader %}
    <!--highcharts -->
        <script src="{% static 'charts/highcharts/highcharts.js' %}"></script>
        <script src="{% static 'charts/highcharts/exporting.js' %}"></script>
        <script src="{% static 'charts/highcharts/highcharts-3d.js' %}"></script>
    <!--highcharts END -->
{% endblock %}
{% block content %}
<div class="panel panel-default" style="text-align:center">
    <div class="panel-heading"><h1>Bitte wählen Sie</h1><br/>
        <select id="chartselector" class="form-control">
                <option value="---">---</option>
                <option value="{% url 'charts:professions' %}">Gefallene nach Beruf</option>
                <option value="{% url 'charts:deaths' %}">Gefallene nach Todesart</option>
        </select>
    </div>
    <div class="panel-body">
        <div id="donut"/>
    </div>
</div>

{% endblock %}
{% block scripts %}
    <script type="text/javascript">
        $("#chartselector").change(function(){
            var which_chart = $("#chartselector option:selected").val();
            console.log(which_chart);
            $.getJSON( which_chart, function( data ) {
                $('html, body').css("cursor", "default");        
                var items = (data.payload).slice(1, data.payload.items);
                var measuredObject = data.measuredObject
                var header = data.title;
                $("h1").text(data.title);
                console.log(items);
                    $('#donut').highcharts({
                        chart: {
                            
                            type: 'pie',
                            options3d: {
                                enabled: true,
                                alpha: 45
                            }
                        },
                        title: {
                        text: ""
                        },
                        subtitle: {
                            text: data.subtitle
                        },
                        plotOptions: {
                            pie: {
                                innerSize: 50,
                                depth: 40
                            }
                        },
                        series: [{
                            name: measuredObject,
                            data:data.payload
                        }]
                    });
            });
        });
    </script>
    <script type="text/javascript" src="{% static 'webpage/libraries/bootstrap335/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'webpage/libraries/bootstrap335/js/bootstrap-tab.js' %}"></script>
    <!-- scroll-up-bottom -->        
    <script type="text/javascript">
            // Setup plugin with default settings
            $(document).ready(function() {
                $.apScrollTop({
                    'onInit': function(evt) {
                        console.log('apScrollTop: init');
                    }
                });
            });
    </script>    
{% endblock %}