browsing/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'persons/$', views.PersonListView.as_view(), name='browse_persons'),
    url(r'^persons/show/$', views.LocatePersons.as_view(), name='person_map'),
]

charts/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^barcharts/$', views.barcharts_view, name='bar_charts'),
    url(r'^testjson/$', views.test_json, name='test_json'),
    url(r'^piecharts/$', views.piecharts_view, name='pie_charts'),
    url(r'^testjsonpie/$', views.test_json_pie, name='test_json_pie'),
    url(r'^professions/$', views.death_by_profession, name='professions'),
    url(r'^deaths/$', views.death_by_death, name='deaths'),
]

totetiroler/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('webpage.urls', namespace='webpage')),
    url(r'^accounts/', include('account.urls', namespace='account')),
    url(r'^places/', include('places.urls', namespace='places')),
    url(r'^persons/', include('persons.urls', namespace='persons')),
    url(r'^datamodel/', include('django_spaghetti.urls', namespace='datamodel')),
    url(r'^browsing/', include('browsing.urls', namespace='browsing')),
    url(r'^charts/', include('charts.urls', namespace='charts')),
    url(r'^social-auth/', include('social.apps.django_app.urls', namespace='social')),
]

browsing/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit


class GenericFilterFormHelper(FormHelper):
    def __init__(self, *args, **kwargs):
        super(GenericFilterFormHelper, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.form_class = 'genericFilterForm'
        self.form_method = 'GET'
        self.add_input(Submit('Filter', 'Filter'))

browsing/views.py
import json
from django_tables2 import SingleTableView, RequestConfig
from persons.models import Person
from places.models import Place
from .filters import PersonListFilter
from .forms import GenericFilterFormHelper
from .tables import PersonTable


class GenericListView(SingleTableView):
    filter_class = None
    formhelper_class = None
    context_filter_name = 'filter'
    paginate_by = 25

    def get_queryset(self, **kwargs):
        qs = super(GenericListView, self).get_queryset()
        self.filter = self.filter_class(self.request.GET, queryset=qs)
        self.filter.form.helper = self.formhelper_class()
        return self.filter.qs

    def get_table(self, **kwargs):
        table = super(GenericListView, self).get_table()
        RequestConfig(self.request, paginate={
            'page': 1, 'per_page': self.paginate_by}).configure(table)
        return table

    def get_context_data(self, **kwargs):
        context = super(GenericListView, self).get_context_data()
        context[self.context_filter_name] = self.filter
        return context


class PersonListView(GenericListView):
    model = Person
    table_class = PersonTable
    template_name = 'browsing/person_list_generic.html'
    filter_class = PersonListFilter
    formhelper_class = GenericFilterFormHelper

    def get_context_data(self, **kwargs):
        context = super(GenericListView, self).get_context_data()
        context[self.context_filter_name] = self.filter
        death = set([x.sterbeort.id for x in Person.objects.all()])
        deathplaces = []
        for x in Place.objects.filter(pk__in=death):
            deathplaces.append(x.name)
        context["deathplaces"] = set(deathplaces)
        brith = set([x.geburtsort.id for x in Person.objects.all()])
        brithplaces = []
        for x in Place.objects.filter(pk__in=brith):
            brithplaces.append(x.name)
        context["brithplaces"] = set(brithplaces)
        return context


class LocatePersons(GenericListView):
    model = Person
    table_class = PersonTable
    template_name = 'browsing/person_map.html'
    filter_class = PersonListFilter
    formhelper_class = GenericFilterFormHelper

    def get_queryset(self, **kwargs):
        qs = Person.objects.exclude(geburtsort__lat__isnull=True)
        self.filter = self.filter_class(self.request.GET, queryset=qs)
        self.filter.form.helper = self.formhelper_class()
        return self.filter.qs

    def get_context_data(self, **kwargs):
        context = super(GenericListView, self).get_context_data()
        context[self.context_filter_name] = self.filter
        lst_json = []
        persons = PersonListFilter(
            self.request.GET,
            queryset=Person.objects.exclude(geburtsort__lat__isnull=True))
        for x in persons:
            if x.geburtsort.lat != "":
                r = {"geometry": {"type": "Point", "coordinates": [
                    float(x.geburtsort.lat),
                    float(x.geburtsort.lng)
                ]},
                    "type": "Feature",
                    "properties": {
                    "popupContent": "<strong>{}</strong>".format(x.name)
                },
                    "id": x.pk}
                lst_json.append(r)
        context["GeoJson"] = json.dumps(lst_json)
        return context

browsing/templates/browsing/generic_list.html
{% extends "webpage/base.html" %}
{% load staticfiles %}
{% block Titel %} {% endblock %}
{% block scriptHeader %}
<!-- CSS jQuery UI -->
<link rel="stylesheet" href="https://code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css"/>
<link rel="stylesheet" type="text/css" href="{% static 'webpage/libraries/jquery.autocomplete/jquery.autocomplete.css' %}"/>
<script src="{% static 'webpage/libraries/jquery.autocomplete/jquery.autocomplete.js' %}"></script>
{% endblock %}
{% block content %}
<div class="container">
<div class="panel panel-default">
    <div class="panel-heading">
    
        <h1>{% block list_title %}{% endblock %}</h1>
    
    {% block create_button %}
        
    {% endblock %}
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-4">
                {% load django_tables2 crispy_forms_tags %}
                {% crispy filter.form filter.form.helper %}
                {% block reset_button %}
                {% endblock %}
            </div>
            <div class="col-md-8">
                {% render_table table %}
            </div>
        </div>
    </div>
</div>
</div>
{% block customScripts %}{% endblock %}
{% endblock %}

browsing/templates/browsing/person_list_generic.html
{% extends "browsing/generic_list.html" %}
{% block Titel %}Suchen und Filtern{% endblock %}
{% block list_title %}Gefallene Tiroler
    {% if user.is_authenticated %}
        | <a class ="btn btn-success"  href="#">Neuen Eintrag anlegen</a>
    {% endif %}
{% endblock %}

{% block reset_button %}
<!-- <a class ="btn btn-default"  id="01">Show/Hide Advanced search options</a></br> -->
 <p></p>
 <a class ="btn btn-default"  href="{% url 'browsing:browse_persons' %}">Filter zurücksetzen</a>     
{% endblock %}

{% block customScripts %}
<script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
<script>

var brithplaces = [{% for name in brithplaces %} "{{ name }}", {% endfor %}];
var deathplaces = [{% for name in deathplaces %} "{{ name }}", {% endfor %}];

    $(function() {
        $("#id_geburtsort__name").autocomplete({
            source:brithplaces
        }); 
    });

    $(function() {
        $("#id_sterbeort__name").autocomplete({
            source:deathplaces
        }); 
    });
</script>
{% endblock %}

browsing/templates/browsing/person_map.html
{% extends "webpage/base.html" %}
{% load staticfiles %}
{% block scriptHeader %}<!--leafletjs -->
   <link rel="stylesheet" href="{% static 'webpage/libraries/leaflet/leaflet.css' %}"/></link>
   <link rel="stylesheet" href="{% static 'webpage/libraries/leaflet.markercluster/dist/MarkerCluster.css' %}"/></link>
   <link rel="stylesheet" href="{% static 'webpage/libraries/leaflet.markercluster/dist/MarkerCluster.Default.css' %}"/></link>

    <script src="{% static 'webpage/libraries/leaflet/leaflet.js' %}"></script>
    <script src="{% static 'webpage/libraries/leaflet.markercluster/src/leaflet.markercluster-src.js' %}"></script>
        <style>
            #map { height: 800px; }
        </style>
{% endblock %}
{% block content %}
<div class="panel panel-default panel-fixed" style="padding:2%; text-align:center;">
<div class="panel-heading">
    <h1> Die Herkunftsorte der Gefallenen </h1>
</div>
<div class="panel-body">
<div class="row">
    <div class="col-md-4">
        <div class="panel panel-default panel-fixed" >
            <div class="panel-heading">
                <h3>Filter</h3>
            </div>
            <div class="panel-body">
            {% load django_tables2 crispy_forms_tags %}
            {% crispy filter.form filter.form.helper %}
            <hr/>
            Results:  <br/>
            {% for obj in filter %}
                <a href="{% url 'persons:person_detail' pk=obj.id %}">{{ obj.name }}</a><br />
            {% endfor %}
            </div>
        </div>
    </div>
    <div class="col-md-8">
        <div class="panel panel-default panel-fixed" >
            <div class="panel-heading">
                <h3>GeoVisualize</h3>
            </div>
            <div class="panel-body">
                <div id="map"></div>
            </div>    
        </div>
    </div>
</div>
</div>
</div>
</div>

<script>
     function filterSet(e, filter) {
        if (e.className === 'btn btn-success') {
        e.className = 'btn btn-default';
        var lg = mapLayerGroups[filter];
        markers.removeLayer(lg);
        } else {
           e.className = 'btn btn-success';
           var lg = mapLayerGroups[filter];
            markers.addLayer(lg);
            mymap.fitBounds(lg.getBounds(), {'maxZoom': 12});
        } };
        var mapLayerGroups = [];
        var markers = L.markerClusterGroup({
        });

    function onEachFeature(feature, layer) {
            var lg = mapLayerGroups[feature.relation_type];
            if (lg === undefined) {
                lg = new L.layerGroup();
                mapLayerGroups[feature.relation_type] = lg;
                $('#filter-menu').append('<a class="btn btn-success" href="#" role="button" onclick="filterSet(this, \''+feature.relation_type+'\')">'+feature.relation_type+'</a>')
            }


            //add the feature to the layer
            lg.addLayer(layer); 
            //mymap.fitBounds(lg.getBounds(), {'maxZoom': 12});

            if (feature.properties && feature.properties.popupContent) {
                popupContent = feature.properties.popupContent;
            }

            layer.bindPopup(feature.properties.popupContent);

        };
        $('#map')
        var mymap = L.map('map', {
          fullscreenControl: true,
          }).setView([47.394167, 13.689167], 8);

        L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
        attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
        maxZoom: 18,
        id: 'mapbox.light',
        accessToken: 'pk.eyJ1Ijoic2VubmllcmVyIiwiYSI6ImNpbHk1YWV0bDAwZnB2dW01d2l1Y3phdmkifQ.OljQLEhqeAygai2y6VoSwQ'
        }).addTo(mymap);



        var build_data =  [{% for obj in filter %}{"geometry": {"type": "Point", "coordinates": [ {{ obj.geburtsort.lng }}, {{ obj.geburtsort.lat }} ]}, "type": "Feature", "properties": {"popupContent": "<strong><a href='{%url 'persons:person_detail' pk=obj.id %}''>{{ obj.name }}, {{ obj.vorname }}</a></strong>" }, "id": "{{ obj.id }}" }{% if forloop.last %}] {% else %},{% endif %}{% empty %}]{% endfor %} 
        var geoJsonLayer = L.geoJson( build_data, {onEachFeature: onEachFeature});
        markers.addLayer(geoJsonLayer);
        mymap.addLayer(markers);
        mymap.fitBounds(markers.getBounds(), {'maxZoom': 12});

</script>
{% endblock %}