charts/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^barcharts/$', views.barcharts_view, name='bar_charts'),
    url(r'^testjson/$', views.test_json, name='test_json'),
    url(r'^piecharts/$', views.piecharts_view, name='pie_charts'),
    url(r'^testjsonpie/$', views.test_json_pie, name='test_json_pie'),
    url(r'^professions/$', views.death_by_profession, name='professions'),
    url(r'^deaths/$', views.death_by_death, name='deaths'),
]

places/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^list/$', views.PlaceListView.as_view(), name='place_list'),
    url(r'^create/$', views.create_place, name='place_create'),
    url(r'^edit/(?P<pk>[0-9]+)$', views.edit_place, name='place_edit'),
    url(r'^delete/(?P<pk>[0-9]+)$', views.PlaceDelete.as_view(), name='place_delete'),
    url(r'^alternativename/list/$', views.AlternativeNameListView.as_view(), name='alternativenames_list'),
    url(r'^alternativename/create/$', views.create_alternativename, name='alternativenames_create'),
    url(r'^alternativename/edit/(?P<pk>[0-9]+)$', views.edit_alternativename, name='alternativenames_edit'),
    url(r'^alternativename/delete/(?P<pk>[0-9]+)$', views.AlternativeNameDelete.as_view(), name='alternativenames_delete')
]

totetiroler/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('webpage.urls', namespace='webpage')),
    url(r'^accounts/', include('account.urls', namespace='account')),
    url(r'^places/', include('places.urls', namespace='places')),
    url(r'^persons/', include('persons.urls', namespace='persons')),
    url(r'^datamodel/', include('django_spaghetti.urls', namespace='datamodel')),
    url(r'^browsing/', include('browsing.urls', namespace='browsing')),
    url(r'^charts/', include('charts.urls', namespace='charts')),
    url(r'^social-auth/', include('social.apps.django_app.urls', namespace='social')),
]

places/models.py
from django.db import models


class AlternativeName(models.Model):
    name = models.CharField(max_length=250, blank=True, help_text="Alternative Name")

    def __str__(self):
        return self.name


class Landgericht(models.Model):
    name = models.CharField(max_length=250, blank=True, help_text="Landgericht")

    def __str__(self):
        return self.name


class Place(models.Model):

    """Holds information about places."""
    name = models.CharField(
        max_length=250, blank=True, help_text="Normalisierte, gegenwärtige Ortsbezeichnung")
    alternative_name = models.ManyToManyField(
        AlternativeName, max_length=250, blank=True, help_text="Alternative names")
    geonames_id = models.CharField(max_length=50, blank=True, help_text="GND-ID")
    lat = models.DecimalField(max_digits=20, decimal_places=12, blank=True, null=True)
    lng = models.DecimalField(max_digits=20, decimal_places=12, blank=True, null=True)
    landgericht = models.ForeignKey(Landgericht, blank=True, null=True)
    comment = models.CharField(max_length=250, blank=True, help_text="Anmerkung, Kommentar")
    legacy_id = models.CharField(max_length=250, blank=True, help_text="alter Identifier")

    def __str__(self):
        if self.alternative_name.exists():
            return self.name + " (" + " ".join([str(x.name) for x in self.alternative_name.all()]) + ")"
        else:
            return self.name

places/forms.py
# -*- coding: utf-8 -*-
from django import forms
from crispy_forms.helper import FormHelper
from .models import Place, AlternativeName


class PlaceForm(forms.ModelForm):
    class Meta:
        model = Place
        fields = ['name', 'alternative_name', 'landgericht', 'geonames_id', 'lat', 'lng']

    def __init__(self, *args, **kwargs):
        super(PlaceForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False


class AlternativeNameForm(forms.ModelForm):
    class Meta:
        model = AlternativeName
        fields = ['name']

    def __init__(self, *args, **kwargs):
        super(AlternativeNameForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False

places/views.py
import requests
import json
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic
from django.views.generic.edit import DeleteView
from django.core.urlresolvers import reverse_lazy

from .models import Place, AlternativeName
from .forms import PlaceForm, AlternativeNameForm


@login_required
def create_place(request):
    if request.method == "POST":
        form = PlaceForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('places:place_list')
        else:
            return render(request, 'places/edit_places.html', {'form': form})
    else:
        form = PlaceForm()
        return render(request, 'places/edit_places.html', {'form': form})


class AlternativeNameListView(generic.ListView):
    template_name = "places/list_alternativenames.html"
    context_object_name = 'object_list'

    def get_queryset(self):
        return AlternativeName.objects.all()


@login_required
def create_alternativename(request):
    if request.method == "POST":
        form = AlternativeNameForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('places:alternativenames_list')
        else:
            return render(request, 'places/edit_alternativenames.html', {'form': form})
    else:
        form = AlternativeNameForm()
        return render(request, 'places/edit_alternativenames.html', {'form': form})


@login_required
def edit_alternativename(request, pk):
    instance = get_object_or_404(AlternativeName, id=pk)
    if request.method == "POST":
        form = AlternativeNameForm(request.POST, instance=instance)
        if form.is_valid():
            form.save()
            return redirect('places:alternativenames_list')
        else:
            return render(
                request, 'places/edit_alternativenames.html', {'form': form, 'instance': instance}
            )
    else:
        form = AlternativeNameForm(instance=instance)
        return render(
            request, 'places/edit_alternativenames.html', {'form': form, 'instance': instance})


class AlternativeNameDelete(DeleteView):
    model = AlternativeName
    template_name = 'webpage/confirm_delete.html'
    success_url = reverse_lazy('places:alternativename_list')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(AlternativeNameDelete, self).dispatch(*args, **kwargs)


class PlaceListView(generic.ListView):
    template_name = "places/list_places.html"
    context_object_name = 'object_list'

    def get_queryset(self):
        return Place.objects.all()


@login_required
def edit_place(request, pk):
    instance = Place.objects.get(id=pk)
    username = "&username=digitalarchiv"
    if request.method == "GET":
        placeName = instance.name
        root = "http://api.geonames.org/searchJSON?q="
        params = "&fuzzy=0.6&lang=de&maxRows=100"
        url = root + placeName + params + username
        try:
            r = requests.get(url)
        except requests.exceptions.RequestException as e:
            url = e
        response = r.text
        responseJSON = json.loads(response)
        responseJSON = responseJSON['geonames']
        form = PlaceForm(instance=instance)
        print(url)
        return render(
            request, 'places/edit_places.html',
            {'object': instance, 'form': form, 'responseJSON': responseJSON}
        )
    else:
        form = PlaceForm(request.POST, instance=instance)
        if form.is_valid():
            form.save()
        return redirect('places:place_list')


class PlaceDelete(DeleteView):
    model = Place
    template_name = 'webpage/confirm_delete.html'
    success_url = reverse_lazy('places:place_list')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(PlaceDelete, self).dispatch(*args, **kwargs)

places/templates/places/edit_alternativenames.html
{% extends "webpage/base.html" %}
{% block Titel %}Edit Places{% endblock %}

{% block scriptHeader %}
<!-- In case you are using any autocomplete-functions, don´t forget to 
    include 'autocomplete_light/static.html
-->
<!--leafletjs -->
    <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.7.5/leaflet.css" />
    <script src="http://cdn.leafletjs.com/leaflet-0.7.5/leaflet.js"></script>
        <style>
            #map { height: 500px; }
        </style>
{% endblock %}

{% block content %}
{% load crispy_forms_tags %}

{% if object %}
<div class="row">
    <div class="col-md-4">
{% endif %}
        <div class="panel panel-default">
            <div class="panel-heading">
                  <h3>{%if object %} Edit {% else %} Create {% endif %}</h3>
            </div>
            <div class="panel-body">
                <form action="" method="post">
                    {% csrf_token %}
                    {% crispy form %}
                    {% if object %}
                    <a class="btn btn-default btn-block" target="_blank">Check<span id="currentID"></span></a>
                    {% endif %}
                    <input class="btn btn-primary btn-block" type="submit" value="Save" />
                    {% if object %}
                    <a class ="btn btn-danger btn-sm" href="{% url 'places:place_delete' pk=object.id %}">delete</a>
                    {% endif %}
                </form>
           </div>
       </div>
{% if object %}       
   </div>
    <div class ="col-md-8">
        <div class="panel panel-default">
            <div class="panel-heading">
                <form class="form-group">
                    <select class="form-control" id="geonamesSELECT">
                            {% if object.geonames_id or object.lat %}
                                <option id="geonamesOption" value="{{ object.name }}_{{ object.lat }}_{{ object.lng }}_{{ object.geonames_id }}">DB-Entry | {{ object.name }} | {{ object.lat }} | {{ object.lng }} | {{ object.geonames_id }}</option>
                            {% endif %}
                            {% for dict in responseJSON %}
                            <option id="geonamesOption" value="{{ dict.countryName }}_{{ dict.name }}_{{ dict.lat }}_{{ dict.lng }}_{{ dict.geonameId }}"> {{ dict.countryName }} | {{ dict.name }} | {{ dict.lat }} | {{ dict.lng }} | {{ dict.geonameId }}</option>
                            {% endfor %}
                        </select>
                    </form>
            </div>
            <div class="panel-body">
                <div id="parentMap"></div>
            </div>
        </div>
    </div>
</div>
{% endif %}
<script type="text/javascript">
    function popupCreateName() {
        var url = "#";
        var MyWindow = window.open(url,"","width=300, height=500");
    }
</script>

<script type="text/javascript">
    $(document).ready(function(){
        $("#id_alternative_name").after('<button id="add_alternativeName" type="button" class="btn btn-sm btn-success" onclick="popupCreateName()"><span class="glyphicon glyphicon-plus"/></button>');
    });
</script>

<script type="text/javascript">
    $( document ).ready(function() {
        $("#map").remove()
        $("#parentMap").append("<div id='map'></div>");
        var placeName = $("#geonamesSELECT option:selected").text();
        var gps1 = placeName.split(/\|/)[2];
        var gps2 = placeName.split(/\|/)[3];
        var map = L.map('map').setView([gps1, gps2], 10);

        L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
        attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
        maxZoom: 18,
        id: 'mapbox.light',
        accessToken: 'pk.eyJ1Ijoic2VubmllcmVyIiwiYSI6ImNpbHk1YWV0bDAwZnB2dW01d2l1Y3phdmkifQ.OljQLEhqeAygai2y6VoSwQ'
        }).addTo(map);

        L.marker([gps1, gps2]).addTo(map)
        .bindPopup(placeName)
        .openPopup();
        });
</script>

<script type="text/javascript">
    $( document ).ready(function(){
        var placeName = $("#geonamesSELECT option:selected").text();
        var gps1 = placeName.split(/\|/)[2];
        var gps2 = placeName.split(/\|/)[3];
        var geonameId = placeName.split(/\|/)[4];
        $('#id_lat').val(parseFloat(gps1));
        $('#id_lng').val(parseFloat(gps2));
        $('#id_geonames_id').val(parseInt(geonameId));
        var gndURL = "http://www.geonames.org/"+geonameId.trim();
        var lookupButton = $("#currentID");
        $(lookupButton).text(gndURL);
        $(lookupButton).parent().attr("href",gndURL);

    });
</script>

<script type="text/javascript">
    $("#geonamesSELECT").change(function(){
        $("#map").remove()
        $("#parentMap").append("<div id='map'></div>");
       var placeName = $("#geonamesSELECT option:selected").text();
        var gps1 = placeName.split(/\|/)[2];
        var gps2 = placeName.split(/\|/)[3];
        var map = L.map('map').setView([gps1, gps2], 15);
        var geonameId = placeName.split(/\|/)[4];
        $('#id_lat').val(parseFloat(gps1));
        $('#id_lng').val(parseFloat(gps2));
        $('#id_geonames_id').val(parseInt(geonameId));
       var gndURL = "http://www.geonames.org/"+geonameId.trim();
        var lookupButton = $("#currentID");
        $(lookupButton).text(gndURL);
        $(lookupButton).parent().attr("href",gndURL);

        L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
        attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
        maxZoom: 18,
        id: 'mapbox.light',
        accessToken: 'pk.eyJ1Ijoic2VubmllcmVyIiwiYSI6ImNpbHk1YWV0bDAwZnB2dW01d2l1Y3phdmkifQ.OljQLEhqeAygai2y6VoSwQ'
        }).addTo(map);
        L.marker([gps1, gps2]).addTo(map)
            .bindPopup(placeName)
            .openPopup();
});
</script>
{% endblock %}

places/templates/places/edit_places.html
{% extends "webpage/base.html" %}
{% load staticfiles %}
{% block Titel %}Edit Places{% endblock %}

{% block scriptHeader %}
<!-- In case you are using any autocomplete-functions, don´t forget to 
    include 'autocomplete_light/static.html
-->
<!--leafletjs -->
    <link rel="stylesheet" href="{% static 'webpage/libraries/leaflet/leaflet.css' %}"/></link>
    <script src="{% static 'webpage/libraries/leaflet/leaflet.js' %}"></script>
        <style>
            #map { height: 500px; }
        </style>
{% endblock %}

{% block content %}
{% load crispy_forms_tags %}

{% if object %}
<div class="row">
    <div class="col-md-4">
{% endif %}
        <div class="panel panel-default">
            <div class="panel-heading">
                  <h3>{%if object %} Edit {% else %} Create {% endif %}</h3>
            </div>
            <div class="panel-body">
                <form action="" method="post">
                    {% csrf_token %}
                    {% crispy form %}
                    {% if object %}
                    <a class="btn btn-default btn-block" target="_blank">Check<span id="currentID"></span></a>
                    {% endif %}
                    <input class="btn btn-primary btn-block" type="submit" value="Save" />
                    {% if object %}
                    <a class ="btn btn-danger btn-sm" href="{% url 'places:place_delete' pk=object.id %}">delete</a>
                    {% endif %}
                </form>
           </div>
       </div>
{% if object %}       
   </div>
    <div class ="col-md-8">
        <div class="panel panel-default">
            <div class="panel-heading">
                <form class="form-group">
                    <select class="form-control" id="geonamesSELECT">
                            {% if object.geonames_id or object.lat %}
                                <option id="geonamesOption" value="{{ object.name }}_{{ object.lat }}_{{ object.lng }}_{{ object.geonames_id }}">DB-Entry | {{ object.name }} | {{ object.lat }} | {{ object.lng }} | {{ object.geonames_id }}</option>
                            {% endif %}
                            {% for dict in responseJSON %}
                            <option id="geonamesOption" value="{{ dict.countryName }}_{{ dict.name }}_{{ dict.lat }}_{{ dict.lng }}_{{ dict.geonameId }}"> {{ dict.countryName }} | {{ dict.name }} | {{ dict.lat }} | {{ dict.lng }} | {{ dict.geonameId }}</option>
                            {% endfor %}
                        </select>
                    </form>
            </div>
            <div class="panel-body">
                <div id="parentMap"></div>
            </div>
        </div>
    </div>
</div>
{% endif %}
<script type="text/javascript">
    function popupCreateName() {
        var url = "{% url 'places:alternativenames_create' %}";
        var MyWindow = window.open(url,"","width=300, height=500");
    }
</script>

<script type="text/javascript">
    $(document).ready(function(){
        $("#id_alternative_name").after('<button id="add_alternativeName" type="button" class="btn btn-sm btn-success" onclick="popupCreateName()"><span class="glyphicon glyphicon-plus"/></button>');
    });
</script>

<script type="text/javascript">
    $( document ).ready(function() {
        $("#map").remove()
        $("#parentMap").append("<div id='map'></div>");
        var placeName = $("#geonamesSELECT option:selected").text();
        var gps1 = placeName.split(/\|/)[2];
        var gps2 = placeName.split(/\|/)[3];
        var map = L.map('map').setView([gps1, gps2], 10);

        L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
        attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
        maxZoom: 18,
        id: 'mapbox.light',
        accessToken: 'pk.eyJ1Ijoic2VubmllcmVyIiwiYSI6ImNpbHk1YWV0bDAwZnB2dW01d2l1Y3phdmkifQ.OljQLEhqeAygai2y6VoSwQ'
        }).addTo(map);

        L.marker([gps1, gps2]).addTo(map)
        .bindPopup(placeName)
        .openPopup();
        });
</script>

<script type="text/javascript">
    $( document ).ready(function(){
        var placeName = $("#geonamesSELECT option:selected").text();
        var gps1 = placeName.split(/\|/)[2];
        var gps2 = placeName.split(/\|/)[3];
        var geonameId = placeName.split(/\|/)[4];
        $('#id_lat').val(parseFloat(gps1));
        $('#id_lng').val(parseFloat(gps2));
        $('#id_geonames_id').val(parseInt(geonameId));
        var gndURL = "http://www.geonames.org/"+geonameId.trim();
        var lookupButton = $("#currentID");
        $(lookupButton).text(gndURL);
        $(lookupButton).parent().attr("href",gndURL);

    });
</script>

<script type="text/javascript">
    $("#geonamesSELECT").change(function(){
        $("#map").remove()
        $("#parentMap").append("<div id='map'></div>");
       var placeName = $("#geonamesSELECT option:selected").text();
        var gps1 = placeName.split(/\|/)[2];
        var gps2 = placeName.split(/\|/)[3];
        var map = L.map('map').setView([gps1, gps2], 15);
        var geonameId = placeName.split(/\|/)[4];
        $('#id_lat').val(parseFloat(gps1));
        $('#id_lng').val(parseFloat(gps2));
        $('#id_geonames_id').val(parseInt(geonameId));
       var gndURL = "http://www.geonames.org/"+geonameId.trim();
        var lookupButton = $("#currentID");
        $(lookupButton).text(gndURL);
        $(lookupButton).parent().attr("href",gndURL);

        L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
        attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
        maxZoom: 18,
        id: 'mapbox.light',
        accessToken: 'pk.eyJ1Ijoic2VubmllcmVyIiwiYSI6ImNpbHk1YWV0bDAwZnB2dW01d2l1Y3phdmkifQ.OljQLEhqeAygai2y6VoSwQ'
        }).addTo(map);
        L.marker([gps1, gps2]).addTo(map)
            .bindPopup(placeName)
            .openPopup();
});
</script>
{% endblock %}

places/templates/places/list_alternativenames.html
{% extends "webpage/base.html" %}
{% block Titel %}Edit Places{% endblock %}

{% block content %}
{% if object_list %}
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default panel-fixed" >
			<div class="panel-heading" style="text-align:center;">
				<h3>Alternative names</h3><a href="{% url 'places:alternativenames_create' %}">(add another Name)</a>
			</div>
			<div class="panel-body">
				<table class="table table-striped">
					<thead>
						<tr>
							<th>Name</th>
						</th>
					</thead>
					<tbody>
						{% for object in object_list %}
						<tr>
							<td><a href="{% url 'places:alternativenames_edit' pk=object.id %}">{{ object }}</a></td>
						</tr>
						{% endfor %}
					</tbody>	
				</table>					
			</div>
		</div>
	</div>
</div>
{% else %}
<h1>no names created yet<h1>

<h2> want to change this? <a href="{% url 'places:alternativenames_create' %}">click me</a>
{% endif %}

{% endblock %}

places/templates/places/list_places.html
{% extends "webpage/base.html" %}
{% load staticfiles %}
{% block Titel %}Edit Places{% endblock %}

{% block scriptHeader %}<!--leafletjs -->
    <link rel="stylesheet" href="{% static 'webpage/libraries/leaflet/leaflet.css' %}"/></link>
    <script src="{% static 'webpage/libraries/leaflet/leaflet.js' %}"></script>
        <style>
            #map { height: 500px; }
        </style>
{% endblock %}
{% block content %}
{% if object_list %}
<div class="row">
	<div class="col-md-4">
		<div class="panel panel-default panel-fixed" >
			<div class="panel-heading" style="text-align:center;">
				<h3>Places</h3><a href="{% url 'places:place_create' %}">(add another Place)</a>
			</div>
			<div class="panel-body">
				<table class="table table-striped">
					<thead>
						<tr>
							<th>Name</th>
							<th>GeoNames</th>
						</th>
					</thead>
					<tbody>
						{% for object in object_list %}
						<tr>
							<td><a href="{% url 'places:place_edit' pk=object.id %}">{{ object }}</a></td>
							<td>{{ object.geonames_id }}</td>
						</tr>
						{% endfor %}
					</tbody>	
				</table>					
			</div>
		</div>
	</div>
	<div class="col-md-8">
		<div class="panel panel-default">
			<div class="panel-heading" style="text-align:center;">
				<h3>Geovisualisation</h3>
			</div>
			<div class="panel-body">
				<div id="parentMap"></div>
			</div>
		</div>
	</div>
</div>


<script type="text/javascript">
	$( document ).ready(function() {
 		$("#map").remove()
    	$("#parentMap").append("<div id='map'></div>");
/*    	var placeName = $("#geonamesSELECT option:selected").text();
    	var gps1 = placeName.split(/\|/)[2];
    	var gps2 = placeName.split(/\|/)[3];*/
    	var map = L.map('map').setView([48.69096, 9.14062], 5);

    	L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
        attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
        maxZoom: 18,
        id: 'mapbox.light',
        accessToken: 'pk.eyJ1Ijoic2VubmllcmVyIiwiYSI6ImNpbHk1YWV0bDAwZnB2dW01d2l1Y3phdmkifQ.OljQLEhqeAygai2y6VoSwQ'
        }).addTo(map);

    	{% for object in object_list %}
    	{% if object.lat %}
    	L.marker([{{ object.lat }}, {{ object.lng }}])
    	.addTo(map)
    	.bindPopup("<h1>{{ object.name }}</h1> <table class='table table-striped'> <tr> <td>Name: </td> <td>{{ object.name }}</td> </tr> </table>");
    	{% endif %}
    	{% endfor %}
		});
</script>
{% endif %}
{% endblock %}