charts/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^barcharts/$', views.barcharts_view, name='bar_charts'),
    url(r'^testjson/$', views.test_json, name='test_json'),
    url(r'^piecharts/$', views.piecharts_view, name='pie_charts'),
    url(r'^testjsonpie/$', views.test_json_pie, name='test_json_pie'),
    url(r'^professions/$', views.death_by_profession, name='professions'),
    url(r'^deaths/$', views.death_by_death, name='deaths'),
]

django_spaghetti/urls.py
from django.conf.urls import url
from django_spaghetti.views import plate

urlpatterns = [
    url(r'^$', plate, name='plate'),
]

totetiroler/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('webpage.urls', namespace='webpage')),
    url(r'^accounts/', include('account.urls', namespace='account')),
    url(r'^places/', include('places.urls', namespace='places')),
    url(r'^persons/', include('persons.urls', namespace='persons')),
    url(r'^datamodel/', include('django_spaghetti.urls', namespace='datamodel')),
    url(r'^browsing/', include('browsing.urls', namespace='browsing')),
    url(r'^charts/', include('charts.urls', namespace='charts')),
    url(r'^social-auth/', include('social.apps.django_app.urls', namespace='social')),
]

webpage/config/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from autocomplete_light import shortcuts as al
al.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('webpage.urls', namespace='webpage'))
]

webpage/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.start_view, name="start"),
    # following url is needed to keep legacy links to this app alive
    url(r'^totetiroler/$', views.start_view, name='start'),
    url(r'^imprint/$', views.imprint_view, name='imprint'),
    url(r'^about/$', views.about_view, name='about'),
]

webpage/forms.py
# -*- coding: utf-8 -*-
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django.core.urlresolvers import reverse
from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Submit, Div


class form_user_login(forms.Form):
	username = forms.CharField(label='Username',widget=forms.TextInput)
	password = forms.CharField(label='Password',widget=forms.PasswordInput)

	def __init__(self, *args, **kwargs):
		super(form_user_login, self).__init__(*args, **kwargs)
		self.helper = FormHelper()
		self.helper.add_input(Submit('submit','Login'))

webpage/views.py
from django.shortcuts import render


def start_view(request):
    context = {}
    return render(request, 'webpage/index.html', context)


def imprint_view(request):
    context = {}
    return render(request, 'webpage/imprint.html', context)


def about_view(request):
    context = {}
    return render(request, 'webpage/about.html', context)

webpage/templates/webpage/about.html
{% extends "webpage/base.html" %}
{% load staticfiles %}
{% load webpage_extras %}
{% block Titel %} About {% endblock %}

{% block content %}
    <div class="container">
        <h1>{% projects_metadata 'title' %}</h1>
    </div>
{% endblock %}

webpage/templates/webpage/base.html
{% load staticfiles %}
{% load webpage_extras %}
{% load account_extras %}

<!DOCTYPE html>
<html lang="en">
  <head>
      <meta charset="utf-8">
      <title>{% block Titel %} {% projects_metadata 'title' %}{% endblock %}</title>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      {% block metaDescription %}
      <meta name="description" content="{{ metadata.description }}">
      {% endblock %}
      <meta name="author" content="{{ metadata.author }}">
      <!-- Bootstrap -->
      <link rel="stylesheet" href="{% static 'webpage/libraries/bootstrap335/css/bootstrap.min.css' %}"/></link>
      <!-- custom css -->
      <link rel="stylesheet" href="{% static 'webpage/css/style.css' %}"/></link>
      <!--scroll to top CSS -->
      <link rel="stylesheet" href="{% static 'webpage/libraries/scroll-to-top/css/ap-scroll-top.min.css'%}"></link>
      <!-- jQuery -->
      <script type="text/javascript" src="{% static 'webpage/libraries/jquery/jquery.js' %}"></script>
      <!--scroll to top -->
      <script src="{% static 'webpage/libraries/scroll-to-top/js/ap-scroll-top.min.js'%}"></script>
      <!-- Piwik -->
        <script type="text/javascript">
          var _paq = _paq || [];
          _paq.push(['trackPageView']);
          _paq.push(['enableLinkTracking']);
          (function() {
            var u="//clarin.oeaw.ac.at/piwik/";
            _paq.push(['setTrackerUrl', u+'piwik.php']);
            _paq.push(['setSiteId', 16]);
            var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
            g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
          })();
        </script>
      <!-- End Piwik -->
      <!-- Begin Cookie Consent plugin by Silktide - http://silktide.com/cookieconsent -->
        <script type="text/javascript">
            window.cookieconsent_options = {"message":"This website uses cookies to ensure you get the best experience on our website","dismiss":"Got it!","learnMore":"More info","link":"{% url 'webpage:imprint' %}","theme":"dark-bottom"};
        </script>
        <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/1.0.9/cookieconsent.min.js"></script>
      <!-- End Cookie Consent plugin -->
      {% block scriptHeader %}
      {% endblock %}
  </head>

  <body role="document">
    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation!</span>
            <span class="icon-bar"/>
            <span class="icon-bar"/>
            <span class="icon-bar"/>
          </button>
        </div>  
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{% projects_metadata 'title' %}
                  <span class="caret"/>
                  </a>
                  <ul class="dropdown-menu">
                    <li>
                        <a href="{% url 'webpage:start' %}">{% projects_metadata 'title' %}</a>
                    </li>
                    <li>
                        <a href="{% url 'datamodel:plate' %}">Datenmodell</a>
                    </li>
                    <li>
                        <a href="{% url 'webpage:imprint' %}">Impressum / Imprint</a>
                    </li>
                  </ul>
                </li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Datenbank
                  <span class="caret"/>
                  </a>
                  <ul class="dropdown-menu">
                    <li>
                        <a href="{% url 'browsing:browse_persons' %}">Suchen und Filtern</a>
                    </li>
                  </ul>
                </li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Analysieren
                  <span class="caret"/>
                  </a>
                  <ul class="dropdown-menu">
                    <li>
                        <a href="{% url 'charts:bar_charts' %}">Balkendiagramm</a>
                    </li>
                    <li>
                        <a href="{% url 'charts:pie_charts' %}">Tortendiagramm</a>
                    </li>
                    <li>
                        <a href="{% url 'browsing:person_map' %}">Herkunftsorte</a>
                    </li>
                  </ul>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li class="dropdown">
                {% if user.is_authenticated %}
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                    <span class="glyphicon glyphicon-user" aria-hidden="true"/>&nbsp;{{ user.get_username }}
                  </a>
                {% else %}
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                    <span class="glyphicon glyphicon-log-in" aria-hidden="true"/>
                  </a>
                {% endif %}
                {% login_tag %}
              </li>
            </ul>
        </div>
    </nav>
    <div class="alert alert-warning">
    <strong>Beta Version!</strong> Änderungen möglich.
    </div>

    <section class="main-content">
      <div id="content" class="container">
        {% block content %}
        {% endblock %}
      </div>
    </section>

    <footer>
      <div class="row text-center">
        <div class="col-sm-4">
          <a href="https://acdh.oeaw.ac.at/acdh/" class="navlink" target="_blank">
              <img src="{% static 'webpage/img/ACDH_kurz_Weiss.png' %}" alt="ACDH" width="25%"/>   
          </a>
        </div>
        <div class="col-sm-4">
            <a href="{% projects_metadata 'github' %}" class="navlink" target="_blank">
              <img src="{% static 'webpage/img/GitHub-Mark-Light-64px.png' %}" alt="{{ metadata.github }}" width="10%"/>   
            </a>
        </div>
        <div class="col-sm-4">
            <a href="https://creativecommons.org/licenses/by-sa/4.0/" class="navlink" target="_blank">
              <img src="{% static 'webpage/img/by-sa.png' %}" alt="CC-BY-SA-4.0" width="25%"/>                 
            </a>
        </div>
      </div>  
    </footer>
    {% block scripts %}
    <script type="text/javascript" src="{% static 'webpage/libraries/bootstrap335/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'webpage/libraries/bootstrap335/js/bootstrap-tab.js' %}"></script>
    <!-- scroll-up-bottom -->        
    <script type="text/javascript">
            // Setup plugin with default settings
            $(document).ready(function() {
                $.apScrollTop({
                    'onInit': function(evt) {
                        console.log('apScrollTop: init');
                    }
                });
            });
    </script>    
    {% endblock %}
  </body>
</html>

webpage/templates/webpage/confirm_delete.html
{% extends "webpage/base.html" %}
{% block content %}

<!-- Launch modal on page load http://stackoverflow.com/questions/10233550/launch-bootstrap-modal-on-page-load -->
<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h3 class="modal-title">Confirm delete</h3>
      </div>
      <div class="modal-body">
       	<form action="" method="post">{% csrf_token %}
    		<h4>Are you sure you want to delete the {{ object.get_classname }}:<br /> <strong>{{ object }}</strong> ?</h4>
    		<input  class="btn btn-danger" type="submit" value="Yes, I want to delete" />
		</form>
      </div>
      <div class="modal-footer">
      </div>
    </div>

  </div>
</div>
</form>
{% endblock content %}
{% block scripts %}
{{block.super}}
<script type="text/javascript">
$(window).load(function(){
        $('#myModal').modal('show');
    });
</script>


{% endblock scripts %}

webpage/templates/webpage/imprint.html
{% extends "webpage/base.html" %}
{% load staticfiles %}
{% load webpage_extras %}
{% block Titel %} Imprint {% endblock %}
{% block content %}
<div class="container">
        <div class="imprint">
            <h1>Impressum | imprint</h1>
            <div lang="ger">
                <h1>Offenlegung gemäß §§ 24, 25 Mediengesetz und § 5 E-Commerce-Gesetz</h1>
                <h2>Medieninhaberin, Herausgeberin, inhaltliche und redaktionelle Verantwortung, Dienstanbieterin:</h2>
                <p>
                    <a href="http://www.oeaw.ac.at">Österreichische Akademie der Wissenschaften</a>
                    <br/>
                    Juristische Person öffentlichen Rechts (BGBl 569/1921 idF BGBl I 130/2003)<br/>
                    <a href="https://acdh.oeaw.ac.at">Austrian Centre for Digital Humanities (ACDH)</a>
                    <br/>
                    Dr. Ignaz Seipel-Platz 2, 1010 Wien, Österreich<br/>
                    E-Mail: <a href="mailto:acdh-tech@oeaw.ac.att" style="color:black">acdh-tech@oeaw.ac.at</a>
                </p>
                <h2>Unternehmensgegenstand:</h2>
                <p>
                    Die Österreichische Akademie der Wissenschaften (ÖAW) hat den gesetzlichen Auftrag, die Wissenschaft in jeder Hinsicht zu fördern. Als Gelehrtengesellschaft pflegt die ÖAW den Diskurs und die Zusammenarbeit der Wissenschaft mit Öffentlichkeit, Politik und Wirtschaft. <br/>
                    Das Austrian Centre for Digital Humanities (ACDH) ist ein Institut der ÖAW, das mit dem Ziel gegründet wurde, digitale Methoden und Ansätze in den geisteswissenschaftlichen Disziplinen zu fördern. Das ACDH unterstützt digitale Forschung in vielfältiger Weise.<br/>
                    {% projects_metadata 'purpose_de' %}
                    
                </p>
                <h2>Vertretungsbefugte Organe:</h2>
                <p>
                    Präsident: Univ.-Prof. Dr. Anton Zeilinger<br/>
                    Vizepräsident: Univ.-Doz. Dr. phil. Michael Alram<br/>
                    Klassenpräsidentin: Univ.-Prof. Dr. Brigitte Mazohl, <br/>
                    Klassenpräsident: Univ.-Prof. Dipl.-Ing. Dr.techn. Georg Brasseur<br/>
                    Als Aufsichtsorgan besteht der Akademierat. Siehe mehr dazu unter <a href="http://www.oeaw.ac.at/die-oeaw/gremien-der-oeaw/akademierat/">http://www.oeaw.ac.at/die-oeaw/gremien-der-oeaw/akademierat/</a>
                </p>
                <h2>Grundlegende Richtung:</h2>
                <p>
                    {% projects_metadata 'purpose_de' %}
                </p>
                <h2>Haftungsausschluss:</h2>
                <p>
                    Die Österreichische Akademie der Wissenschaften übernimmt keinerlei Gewähr für die Aktualität, Korrektheit, Vollständigkeit oder Qualität der bereitgestellten Informationen.<br/>
                    Im Falle des Bestehens von Links auf Webseiten anderer Medieninhaber, für deren Inhalt die ÖAW weder direkt oder indirekt mitverantwortlich ist, übernimmt die ÖAW keine Haftung für deren Inhalte und schließt jegliche Haftung hierfür aus.
                    
                </p>
                <h2>Urheberrechtlicher Hinweis:</h2>
                <p>
                    Diese Seite und ihre Inhalte sind, sofern nicht anders gekennzeichnet, unter der creative commons Lizenz <a href="http://creativecommons.org/licenses/by-sa/4.0/">CC-BY-SA 4.0</a> International lizensiert (Namensnennung – Weitergabe unter gleichen Bedingungen).
                </p>
                <h2>Datenschutzrechtlicher Hinweis:</h2>
                <p>
                    Wir weisen darauf hin, dass zum Zwecke der Systemsicherheit und der Übersicht über das Nutzungsverhalten der Besuchenden im Rahmen von Cookies diverse personenbezogene Daten (Besuchszeitraum, Betriebssystem, Browserversion, innere Auflösung des Browserfensters, Herkunft nach Land, wievielter Besuch seit Beginn der Aufzeichnung) mittels <a href="http://piwik.org/">Piwik-Tracking</a> gespeichert werden. Die Daten werden bis auf weiteres gespeichert. Soweit dies erfolgt, werden diese Daten nicht ohne Ihre ausdrückliche Zustimmung an Dritte weitergegeben.<br/>
                    Durch die Nutzung der Website erklären Sie sich mit der Art und Weise sowie dem Zweck der Datenverarbeitung einverstanden. Durch eine entsprechende Einstellung in Ihrem Browser können Sie die Speicherung der Cookies verhindern. In diesem Fall stehen Ihnen aber gegebenenfalls nicht alle Funktionen der Website zur Verfügung.<br/>
                    Die im Rahmen der Impressumspflicht veröffentlichten Kontaktdaten dürfen von Dritten nicht zur Übersendung von nicht ausdrücklich angeforderter Werbung und Informationsmaterialien verwendet werden. Einer derartigen Verwendung wird hiermit ausdrücklich widersprochen.
                    
                </p>
            </div>
            <hr/>
            <div lang="eng">
                <h1>Legal disclosure according to §§ 24, 25 Austrian media law and § 5 E-Commerce law</h1>
                <h2>Media owner, publisher, responsible for content and editorial office, service provider:</h2>
                <p>
                    <a href="http://www.oeaw.ac.at">Austrian Academy of Sciences</a>
                    <br/>
                    Corporate body organized under public law (BGBl 569/1921 idF BGBl I 130/2003)<br/>
                    <a href="https://acdh.oeaw.ac.at">Austrian Centre for Digital Humanities (ACDH)</a>
                    <br/>
                    Dr. Ignaz Seipel-Platz 2, 1010 Vienna, Austria<br/>
                    E-Mail: <a href="mailto:acdh-tech@oeaw.ac.att" style="color:black">acdh-tech@oeaw.ac.at</a>
                </p>
                <h2>Nature and purpose of the business:</h2>
                <p>
                    The Austrian Academy of Sciences (OEAW) has the legal duty to support the sciences and humanities in every respect. As a learned society, the OEAW fosters discourse and cooperation between science and society, politics and economy.<br/>
                    The Austrian Centre for Digital Humanities (ACDH) is an OEAW institute founded with the goal to support digital methods in arts and humanities disciplines. The ACDH supports digital research in manifold ways.<br/>
                    {% projects_metadata 'purpose_en' %}
                </p>
                <h2>Signing power:</h2>
                <p>
                    President: Univ.-Prof. Dr. Anton Zeilinger<br/>
                    Vice president: Univ.-Doz. Dr. phil. Michael Alram<br/>
                    Class presidents: Univ.-Prof. Dr. Brigitte Mazohl, Univ.-Prof. Dipl.-Ing. Dr.techn. Georg Brasseur<br/>
                    Supervisory body:  Academy council. For more information, please visit <a href="http://www.oeaw.ac.at/die-oeaw/gremien-der-oeaw/akademierat/">http://www.oeaw.ac.at/die-oeaw/gremien-der-oeaw/akademierat/</a>
                </p>
                <h2>Main aim:</h2>
                <p>
                    {% projects_metadata 'purpose_en' %}
                </p>
                <h2>Disclaimer:</h2>
                <p>
                    The Austrian Academy of Sciences does not take responsibility for the nature, accuracy, entirety or quality of the provided information.<br/>
                    In the case of links to websites of other media owners, whose content the OEAW is neither directly nor indirectly responsible for, the OEAW does not assume liability for their content and excludes any liability in this case.
                </p>
                <h2>Copyright notice:</h2>
                <p>
                    This website and its content is, unless indicated otherwise, licensed under a creative commons <a href="http://creativecommons.org/licenses/by-sa/4.0/">CC-BY-SA 4.0</a> International license (Attribution – Share alike).
                </p>
                <h2>Data privacy notice:</h2>
                <p>
                    This is a notice to indicate that for reasons of system security and overview of user behavior, personal data of users of this website (visiting period, operating system, browser version, browser resolution, country of origin, number of visits) will be stored using cookies and <a href="http://piwik.org/">piwik tracking</a>. Data will be stored until further notice. Data will not be disseminated without your explicit consent.<br/>
                    By using this website, you agree to the manner and purposes of data processing. You can disable cookies in your browser settings. However, this might limit functionality of this website.<br/>
                    The contact data published in the context of the imprint duty may not be used to send promotional or informational material not explicitly requested. We explicitly disagree with this usage. 
                </p>
            </div>
        </div>
    </div>
{% endblock %}

webpage/templates/webpage/index.html
{% extends "webpage/base.html" %}
{% load staticfiles %}
{% load webpage_extras %}
{% block content %}

<div class="container text-center">
    <div id="myCarousel" class="carousel slide" data-ride="carousel"><!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"/>
            <li data-target="#myCarousel" data-slide-to="1"/>
            <li data-target="#myCarousel" data-slide-to="2"/>
        </ol><!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
            <div class="item active">
                <img src="{% static 'webpage/img/Albin_Egger-Lienz_002.jpg' %}" alt="First" width="1200" height="600" title="Egger-Lienz - Haspinger Anno Neun. https://commons.wikimedia.org/wiki/Category:Tyrolean_Rebellion"/>
                <div class="carousel-caption">
                    <h3>Der Totentanz von Anno Neun</h3>
                    <p>Egger-Lienz</p>
                    <p>Distributed by <a href="//commons.wikimedia.org/wiki/Commons:10,000_paintings_from_Directmedia" title="Commons:10,000 paintings from Directmedia">DIRECTMEDIA</a> Publishing GmbH., Gemeinfrei, https://commons.wikimedia.org/w/index.php?curid=150606</p>
                </div>
            </div>
            <div class="item">
                <img src="{% static 'webpage/img/Egger-Lienz_-_Haspinger_Anno_Neun_-_1908-09.jpg' %}" alt="First" width="1200" height="600" title="Egger-Lienz - Haspinger Anno Neun. https://commons.wikimedia.org/wiki/Category:Tyrolean_Rebellion"/>
                <div class="carousel-caption">
                    <h3>Haspinger Anno Neun</h3>
                    <p>Egger-Lienz</p>
                    <p>https://commons.wikimedia.org/wiki/Category:Tyrolean_Rebellion</p>
                </div>
            </div>
            <div class="item">
                <img src="{% static 'webpage/img/The_Last_Reserves_Franz_von_Defregger_1872.jpg' %}" alt="a nice feature picture" width="1200" height="600" title="La dernière levée. Franz von Defregger 1872. Neue Pinakothek, Inv Nr 9030. https://commons.wikimedia.org/wiki/Category:Tyrolean_Rebellion"/>
                <div class="carousel-caption">
                    <h3>Das letzte Aufgebot</h3>
                    <p>Franz Defregger</p>
                    <p>By <a href="//commons.wikimedia.org/wiki/User:Yelkrokoyade" title="User:Yelkrokoyade">Yelkrokoyade</a> - <span class="int-own-work" lang="en">Own work</span>, <a href="http://creativecommons.org/licenses/by-sa/4.0" title="Creative Commons Attribution-Share Alike 4.0">CC BY-SA 4.0</a></p>
                </div>
            </div>
        </div><!-- Left and right controls -->
        <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev"><!--<span class="sr-only">Previous</span>--></a>
        <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next"><!--<span class="sr-only">Next</span>--></a>
    </div>
    <h1 style="text-align:center">{% projects_metadata 'title' %}</h1>
    <h3>{% projects_metadata 'subtitle' %}</h3>
    <p>Der Aufstand Teile der Tiroler Bevölkerung im Jahr 1809 gegen die bayerische Obrigkeit ist bis heute ein bedeutender Baustein im Tiroler Geschichtsbild. Die Gefallenen dieser Erhebung können mittels mit Hilfe dieser Website nun erstmals online recherchiert werden. <br/> Die in dieser Auflistung verzeichneten Daten stammen aus <a href="http://search.obvsg.at/UIB:Blended:UIB_aleph_acc000119944">Hans Kramer, Die Gefallenen Tirols 1796-1813 (Schlern-Schriften 47), Innsbruck 1949</a> und wurden im Zuge einer Diplomarbeit systematisch erhoben. Mehr dazu kann in der entsprechenden Arbeit <a href="http://search.obvsg.at/UIB:Blended:UIB_aleph_acc001586080">Andorfer, Totetiroler, Innsbruck 2009</a> nachgelesen werden.<a href="{% static 'webpage/pdf/Andorfer_Totetiroler_2009.pdf' %}">[download]</a>.</p>
</div>

{% endblock %}